### ISSUE TITLE
Informations for BioMA-SWAT variables

### ISSUE THREAD

**Issue by TeikiRah** [AgriculturalModelExchangeInitiative/SoilTemperatureModels#13]
- **SoilTemperatureByLayers** is not initialized, what value should I use ?
- **SurfaceSoilTemperature** is not initialized, what value should I use ?

**Comment by fumagallidavide** [comment]
In the VarInfo definitions the default values are:
SoilTemperatureByLayers : 15 C

SurfaceSoilTemperature : 25 C
