### ISSUE TITLE
SIRIUS-Quality Double definition of variable at Fortran functions

### ISSUE THREAD

**Issue by fabiooliveira72** [AgriculturalModelExchangeInitiative/SoilTemperatureModels#16]
File calculatesoiltemperature.f90 at function UpdateTemperature has a double definition of variable 'Temperature'. 

It needs to be checked if this is right or wrong. Because there is a compilation error where one is output and input at same time.

The code was changed manually. Input function variable Temperature was modified to Temp.

**Comment by cyrillemidingoyi** [comment]
Resolved
