### ISSUE TITLE
Campbell Model

### ISSUE THREAD

**Issue by pradal** [AgriculturalModelExchangeInitiative/SoilTemperatureModels#25]
# Set of codes 
- [x] Use only CamelCase to name Model name
- [x] Function that is used several times is duplicated (Divide). PyCrop2ML must manage namespace or just generate once a function
- [x] the variable i is used to loop with arrays. So it becomes a reserved variable. Do not used it!
- [x] Does array can be allocated in the model or in functions? How it is manage for the different languages

**Comment by TeikiRaihauti** [comment]
In a function, seems like arrays can't be initialized with arguments of the function
