### ISSUE TITLE
Stics algorithm feature: nint, where

### ISSUE THREAD

**Issue by cyrillemidingoyi** [AgriculturalModelExchangeInitiative/SoilTemperatureModels#3]
@plecharpent Fortran transformer doesn't not apply nint function to an array variable. It does't nost also transform "where statement". Please could you change this.

**Comment by plecharpent** [comment]
@cyrillemidingoyi I fixed this issue and pushed into the SoilTemperatureModels but the conversion with cyml still fail.
Then I updated conda, created a new environment and installed PyCrop2ML, but I face the same errors

```
Traceback (most recent call last):
  File "/home/plecharpent/miniconda3/envs/amei_27_02_2023/bin/cyml", line 11, in <module>
    load_entry_point('pycropml==1.1.0', 'console_scripts', 'cyml')()
  File "/home/plecharpent/miniconda3/envs/amei_27_02_2023/lib/python3.7/site-packages/pycropml-1.1.0-py3.7.egg/pycropml/main.py", line 119, in main
    status = transpile_package(sourcef, language)
  File "/home/plecharpent/miniconda3/envs/amei_27_02_2023/lib/python3.7/site-packages/pycropml-1.1.0-py3.7.egg/pycropml/cyml.py", line 73, in transpile_package
    T = Topology(namep,package)
  File "/home/plecharpent/miniconda3/envs/amei_27_02_2023/lib/python3.7/site-packages/pycropml-1.1.0-py3.7.egg/pycropml/topology.py", line 98, in __init__
    composite_file = self.data.glob("composition*.xml")[0]
IndexError: list index out of range
```
Thanks for your help.

**Comment by pradal** [comment]
I had the same error yesterday.
This was due to a wrong command line.

cyml -p mydir f90

where mydir is a directory containing crop2ml

**Comment by plecharpent** [comment]
But my intent is to create the crop2ml package first and the use of the -c option and an error 
is displayed at the end of the Usage
```
Usage: cyml [options] package language1 [languages]

cyml transpiler translate a cyml source code or a Crop2ML package with algo in cyml
language to target language.

Example
    cyml <source_code.pyx or pkg> <target_language>

    * target language must be:
        py for python
        cs for csharp
        f90 for fortran
        java for java
        simplace for simplace
        sirius for sirius

cyml: error: no such option: -c
```

**Comment by pradal** [comment]
Yes, sorry. On which OS are you?Oups, sorry. It seems you ar eon Linux.
Could you update the pacage first?

    conda install -c amei -c openalea3 -c conda-forge "pycropml==1.2.2"
When I do 

    cyml -c Stics_soil_temperature Stics_soil_temperature stics

I have the following error 
```python
Traceback (most recent call last):
  File "/Users/pradal/miniconda3/envs/paackcml/bin/cyml", line 33, in <module>
    sys.exit(load_entry_point('pycropml==1.2.1', 'console_scripts', 'cyml')())
  File "/Users/pradal/devlp/git/PyCrop2ML/src/pycropml/main.py", line 137, in main
    status = transpile_component(sourcef,newpackage,language)
  File "/Users/pradal/devlp/git/PyCrop2ML/src/pycropml/cyml.py", line 201, in transpile_component
    translator[language](component, package)
  File "/Users/pradal/devlp/git/PyCrop2ML/src/pycropml/transpiler/antlr_py/stics/run.py", line 122, in run_stics
    fil = open(os.path.join(component, f), "r")
FileNotFoundError: [Errno 2] No such file or directory: Path('Stics_soil_temperature/test_soiltemp_component.f90')
```

**Comment by plecharpent** [comment]
I reinstalled pycropml as you mentioned before:
```
conda install -c amei -c openalea3 -c conda-forge "pycropml==1.2.2"
```
And it works executing 
```
cyml -c Stics_soil_temperature Stics_soil_temperature stics
```
But only with the f90 files of the last sprint in october 2022.
With the version I pushed on the SoilTemperatureModels repos recently the use of the casting function `int` to convert real number to integer is apparently not supported.

In addition, I think that the cyml Usage (of version 1.2.2 I installed) is not complete because stics is not appearing as a platform name as in the used command and using f90 is failing
```
Usage: cyml [options] package language1 [languages]

cyml transpiler translate a cyml source code or a Crop2ML package with algo in cyml
language to target language.

Example
    cyml <source_code.pyx or pkg> <target_language>

    * target language must be:
        py for python
        cs for csharp
        f90 for fortran
        java for java
        simplace for simplace
        sirius for sirius
        openalea for OpenAlea
        cpp for C++
        r for r

```

**Comment by pradal** [comment]
The problem is that you use the conversion on an array and not on a number.
Can you change this?

**Comment by pradal** [comment]
@plecharpent : We have several problems with your soil temperature model:

1. int on array do not work.
We try to modify that by a loop

2. **count** function is not supported by cyml.
We also convert it by a loop

3. Computing the size in the declaration is also not supported
```fortran
REAL, INTENT(OUT)   ::  layer_temp(size(layer_thick))
```

While I have fixed the two first problems, I can not fix the last one.
Could you modify the code to solve this problem?

**Comment by pradal** [comment]
Also we need to remove the f90 files in the tests dir. I will remove the tests first

**Comment by pradal** [comment]
Thanks.
The modifications have been pushed in github.
Just pull it.

**Comment by plecharpent** [comment]
I fixed array declaration using size() for dimensionning them with allocatable arrays.
But there are still errors when creating the Crop2ML package. The Traceback is very long, I put here after 
the beginning and the last lines.

```bash
cyml -c Stics_soil_temperature Stics_soil_temperature stics
dsorted donce
{}
ALLOCATED jjhhhhhhhhh
Traceback (most recent call last):
...

res = self.translate_func(func, args, location)
  File "/home/plecharpent/miniconda3/envs/amei_27_02_2023/lib/python3.7/site-packages/pycropml-1.2.2-py3.7.egg/pycropml/transpiler/antlr_py/fortran/fortranTransformer.py", line 2015, in translate_func
    if fname in c:
TypeError: argument of type 'NoneType' is not iterable

```

I am using the PyCrop2ML 1.2.2 as you told me yesterday Christophe.

**Comment by pradal** [comment]
I get the same error. I will investigate!

**Comment by pradal** [comment]
The ALLOCATED is not considered by PyCrop2ML.
@cyrillemidingoyi ?

**Comment by plecharpent** [comment]
I can try to remove the tests using ALLOCATED to be sure.

**Comment by pradal** [comment]
Please, do that...
No equivalent in some other languages

**Comment by plecharpent** [comment]
I get the same errors after that, finally I am wondering if the dynamic memory allocation is taken into account in the translator ?

**Comment by plecharpent** [comment]
I don't know if in DSSAT they use allocation

**Comment by plecharpent** [comment]
Not any more previous errors without calling ALLOCATED, but there is still an error when apparently (if I understand well) using the cast function `int` as it appears at the end of the Traceback. See KeyError: 'int' at the end
```
cyml -c Stics_soil_temperature Stics_soil_temperature stics
dsorted donce
{}
dictdooopp
{}
{'temp_profile': [':'], 'layer_thick': [':'], 'layer_temp': [':'], 'up_depth': [':'], 'layer_depth': [':']}
Traceback (most recent call last):

.....

File "/home/plecharpent/miniconda3/envs/amei_27_02_2023/lib/python3.7/site-packages/pycropml-1.2.2-py3.7.egg/pycropml/transpiler/generators/cymlGenerator.py", line 170, in visit_standard_method_call
    z = self.methods[l][node.message]
KeyError: 'int'

```

**Comment by plecharpent** [comment]
I removed the Layerstemp.f90 module which is not used by the composition model.
But the transformation into is uncomplete.
Here is the command output
```cyml -c Stics_soil_temperature Stics_soil_temperature stics
dsorted donce
{}
dictdooopp
{}
{}
{}
{'prev_temp_profile': [':'], 'temp_profile': [':'], 'vexp': [':']}
{}
[{'target': 'temp_amp.min_temp', 'source': 'min_temp'}, {'target': 'temp_amp.max_temp', 'source': 'max_temp'}]
```
In the crop2ml directory some files are missing 
![image](https://user-images.githubusercontent.com/3098097/222179602-1fc79d0d-acef-4334-90d3-e74537826ac7.png)

**Comment by pradal** [comment]
Yes. Thermamp is not considerred.
We have to investigate it.

**Comment by plecharpent** [comment]
I found the problem the !%%CyML Model End%% annotation was missing.
I generated the crop2ml package. 
![image](https://user-images.githubusercontent.com/3098097/222184629-2f1b7521-1b7e-4960-bdb4-8abb7dd76ae2.png)

I will push it

**Comment by pradal** [comment]
Do not seems to be fixed yet

**Comment by plecharpent** [comment]
Yes after the fix done by Cyrille on the model name in the Temprofile.f90 meta data
the conversion is complete.
Thanks.
