### ISSUE TITLE
DSSAT_EPICST component

### ISSUE THREAD

**Issue by cyrillemidingoyi** [AgriculturalModelExchangeInitiative/SoilTemperatureModels#8]
@fabiooliveira72 
@chporter 
You have made changes (assign TDL at 0.0) in the "rate calculation" part and I would like to know if it should be so.
# rate calculation
        TDL = 0.0
Is it not the value calculated by the initialization that should be used and updated day by day (like in your original code?

**Comment by cyrillemidingoyi** [comment]
@fabiooliveira72 
In the subroutine SOIL_EPIC, TMA, X2_PREV and ST are InOut

**Comment by fabiooliveira72** [comment]
@cyrillemidingoyi I think it was a mistake that I did converting the code. I look at it again and it seems TDL needs to hold the value daily.
